### ISSUE TITLE
Me genera error usando xampp en windows

### ISSUE THREAD

**Issue by johnfelipe** [andresfranco/CV2#1]
![login](https://cloud.githubusercontent.com/assets/428820/11408460/46b84ea6-9387-11e5-86c0-fba7eb859b75.png)

**Comment by johnfelipe** [comment]
Importe initialdata.sql y ya puedo ingresar correctamente, pero en
http://localhost/CV2:

![not](https://cloud.githubusercontent.com/assets/428820/11408520/b09bf6ec-9387-11e5-9ba7-be970d1c3724.png)

**Comment by johnfelipe** [comment]
No puedo agregar nada aun, me puedes ayudar?

**Comment by andresfranco** [comment]
Este error sale cuando accesas a una ruta no válida

1.Verifica que el .htaccess este configurado asi:

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
1. Al iniciar en : localhost://CV2/login 

Puedes acceder con el usuario admin ? y te muestra la pantalla principal?
cuando tratas de acceder a que sección te muestra el 404?

**Comment by johnfelipe** [comment]
el htacces esta

```
RewriteEngine On

# Some hosts may require you to use the `RewriteBase` directive.
# If you need to use the `RewriteBase` directive, it should be the
# absolute physical path to the directory that contains this htaccess file.
#
# RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

http://localhost/CV2/login

![admin](https://cloud.githubusercontent.com/assets/428820/11409453/0d60cb7c-938e-11e5-9e27-a015cace07d8.png)

Cuando entro a curriculum no me deja añadir nada

![noadd](https://cloud.githubusercontent.com/assets/428820/11409458/17dcda50-938e-11e5-94e2-a076aa0a4c5c.png)

**Comment by johnfelipe** [comment]
Como resuelvo eso?

**Comment by andresfranco** [comment]
Lo que esta pasando es que no tienes asociada la data de acciones y roles , por eso el usuario admin no tiene permisos para crear , editar o eliminar curricullums , debes tener creadas las acciones  y asociar las acciones al rol de admin .

con este script de datos te debe funcionar

## 

## -- Volcar la base de datos para la tabla `userrole`

INSERT INTO `userrole` VALUES (1, 1, 'admin', '2015-03-04 11:25:23', 'admin', '2015-03-04 11:25:23');

---

## 

## -- Volcar la base de datos para la tabla `action`

INSERT INTO `action` VALUES (14, 'Create User', 'Permission for create backend users', 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:56:21');
INSERT INTO `action` VALUES (15, 'Edit User', 'Edit User', 'admin', '2015-05-05 23:35:15', 'admin', '2015-05-05 23:35:15');
INSERT INTO `action` VALUES (16, 'Delete User', 'Delete User', 'admin', '2015-05-05 23:35:31', 'admin', '2015-05-05 23:35:31');
INSERT INTO `action` VALUES (17, 'View User', 'View User', 'admin', '2015-05-05 23:36:41', 'admin', '2015-05-05 23:36:41');
INSERT INTO `action` VALUES (18, 'Create Role', 'Create Role', 'admin', '2015-05-06 17:15:09', 'admin', '2015-05-06 17:15:09');
INSERT INTO `action` VALUES (19, 'Edit Role', 'Edit Role', 'admin', '2015-05-06 17:15:25', 'admin', '2015-05-06 17:15:25');
INSERT INTO `action` VALUES (20, 'Delete Role', 'Delete Role', 'admin', '2015-05-06 17:15:46', 'admin', '2015-05-06 17:15:46');
INSERT INTO `action` VALUES (21, 'View Role', 'View Role', 'admin', '2015-05-06 17:16:04', 'admin', '2015-05-06 17:16:04');
INSERT INTO `action` VALUES (22, 'Create Action', 'Create Action', 'admin', '2015-05-06 17:20:46', 'admin', '2015-05-06 17:20:46');
INSERT INTO `action` VALUES (23, 'Edit Action', 'Edit Action', 'admin', '2015-05-06 17:21:04', 'admin', '2015-05-06 17:21:04');
INSERT INTO `action` VALUES (24, 'Delete Action', 'Delete Action', 'admin', '2015-05-06 17:21:23', 'admin', '2015-05-06 17:21:23');
INSERT INTO `action` VALUES (25, 'View Action', 'View Action', 'admin', '2015-05-06 17:34:08', 'admin', '2015-05-06 17:34:08');
INSERT INTO `action` VALUES (26, 'Create Parameter', 'Create Parameter', 'admin', '2015-05-21 09:48:46', 'admin', '2015-05-21 09:48:46');
INSERT INTO `action` VALUES (27, 'Update Parameter', 'Update Parameter', 'admin', '2015-05-21 09:49:03', 'admin', '2015-05-21 09:49:03');
INSERT INTO `action` VALUES (28, 'Delete Parameter', 'Delete Parameter', 'admin', '2015-05-21 09:49:25', 'admin', '2015-05-21 09:49:25');
INSERT INTO `action` VALUES (29, 'View Parameter', 'View Parameter', 'admin', '2015-05-21 09:49:41', 'admin', '2015-05-21 09:49:41');
INSERT INTO `action` VALUES (30, 'Create Language', 'Create Language', 'admin', '2015-05-21 09:50:20', 'admin', '2015-05-21 09:50:20');
INSERT INTO `action` VALUES (31, 'Edit Language', 'Edit Language', 'admin', '2015-05-21 09:50:32', 'admin', '2015-05-21 09:50:32');
INSERT INTO `action` VALUES (32, 'Delete Language', 'Delete Language', 'admin', '2015-05-21 09:50:53', 'admin', '2015-05-21 09:50:53');
INSERT INTO `action` VALUES (33, 'View Language', 'View Language', 'admin', '2015-05-21 09:51:05', 'admin', '2015-05-21 09:51:05');
INSERT INTO `action` VALUES (34, 'Create Curricullum', 'Create Curricullum', 'admin', '2015-05-21 09:51:38', 'admin', '2015-05-21 09:51:38');
INSERT INTO `action` VALUES (35, 'Edit Curricullum', 'Edit Curricullum', 'admin', '2015-05-21 09:51:54', 'admin', '2015-05-21 09:51:54');
INSERT INTO `action` VALUES (36, 'Delete Curricullum', 'Delete Curricullum', 'admin', '2015-05-21 09:52:13', 'admin', '2015-05-21 09:52:13');
INSERT INTO `action` VALUES (37, 'View Curricullum', 'View Curricullum', 'admin', '2015-05-21 09:52:27', 'admin', '2015-05-21 09:52:27');
INSERT INTO `action` VALUES (38, 'Create Education', 'Create Education', 'admin', '2015-05-21 10:20:49', 'admin', '2015-05-21 10:20:49');
INSERT INTO `action` VALUES (39, 'Edit Education', 'Edit Education', 'admin', '2015-05-21 10:21:08', 'admin', '2015-05-21 10:21:08');
INSERT INTO `action` VALUES (40, 'Delete Education', 'Delete Education', 'admin', '2015-05-21 10:21:52', 'admin', '2015-05-21 10:21:52');
INSERT INTO `action` VALUES (41, 'View Education', 'View Education', 'admin', '2015-05-21 10:22:59', 'admin', '2015-05-21 10:22:59');
INSERT INTO `action` VALUES (42, 'Create Work', 'Create Work', 'admin', '2015-05-21 10:23:20', 'admin', '2015-05-21 10:23:20');
INSERT INTO `action` VALUES (43, 'Edit Work', 'Edit Work', 'admin', '2015-05-21 10:26:57', 'admin', '2015-05-21 10:26:57');
INSERT INTO `action` VALUES (44, 'Delete Work', 'Delete Work', 'admin', '2015-05-21 10:27:14', 'admin', '2015-05-21 10:27:14');
INSERT INTO `action` VALUES (45, 'View Work', 'View Work', 'admin', '2015-05-21 10:27:27', 'admin', '2015-05-21 10:27:27');
INSERT INTO `action` VALUES (46, 'Create Skill', 'Create Skill', 'admin', '2015-05-21 10:31:42', 'admin', '2015-05-21 10:31:42');
INSERT INTO `action` VALUES (47, 'Edit Skill', 'Edit Skill', 'admin', '2015-05-21 10:31:56', 'admin', '2015-05-21 10:31:56');
INSERT INTO `action` VALUES (48, 'Delete Skill', 'Delete Skill', 'admin', '2015-05-21 10:32:08', 'admin', '2015-05-21 10:32:08');
INSERT INTO `action` VALUES (49, 'View Skill', 'View Skill', 'admin', '2015-05-21 10:32:30', 'admin', '2015-05-21 10:32:30');
INSERT INTO `action` VALUES (50, 'Create Project', 'Create Project', 'admin', '2015-05-21 10:33:04', 'admin', '2015-05-21 10:33:04');
INSERT INTO `action` VALUES (51, 'Edit Project', 'Edit Project', 'admin', '2015-05-21 10:33:18', 'admin', '2015-05-21 10:33:18');
INSERT INTO `action` VALUES (52, 'Delete Project', 'Delete Project', 'admin', '2015-05-21 10:33:37', 'admin', '2015-05-21 10:33:37');
INSERT INTO `action` VALUES (53, 'View Project', 'View Project', 'admin', '2015-05-21 10:34:47', 'admin', '2015-05-21 10:34:47');
INSERT INTO `action` VALUES (54, 'Create Translation', 'Create Translation', 'admin', '2015-05-21 10:35:11', 'admin', '2015-05-21 10:35:11');
INSERT INTO `action` VALUES (55, 'Edit Translation', 'Edit Translation', 'admin', '2015-05-21 10:35:23', 'admin', '2015-05-21 10:35:23');
INSERT INTO `action` VALUES (56, 'Delete Translation', 'Delete Translation', 'admin', '2015-05-21 10:35:35', 'admin', '2015-05-21 10:35:35');
INSERT INTO `action` VALUES (57, 'View Translation', 'View Translation', 'admin', '2015-05-21 10:35:49', 'admin', '2015-05-21 10:35:49');

## 

## -- Volcar la base de datos para la tabla `role`

INSERT INTO `role` VALUES (1, 'administrator', 'System administrator', 'admin', '2015-05-05 16:42:26', 'admin', '2015-05-05 16:43:05');

---

## 

## -- Volcar la base de datos para la tabla `roleaction`

INSERT INTO `roleaction` VALUES (1, 14, 'admin', '2015-05-06 15:52:13', 'admin', '2015-05-06 15:52:13');
INSERT INTO `roleaction` VALUES (1, 15, 'admin', '2015-05-06 16:05:48', 'admin', '2015-05-06 16:05:48');
INSERT INTO `roleaction` VALUES (1, 16, 'admin', '2015-05-06 16:57:51', 'admin', '2015-05-06 16:57:51');
INSERT INTO `roleaction` VALUES (1, 17, 'admin', '2015-05-06 17:17:07', 'admin', '2015-05-06 17:17:07');
INSERT INTO `roleaction` VALUES (1, 18, 'admin', '2015-05-06 17:17:31', 'admin', '2015-05-06 17:17:31');
INSERT INTO `roleaction` VALUES (1, 19, 'admin', '2015-05-06 17:18:43', 'admin', '2015-05-06 17:18:43');
INSERT INTO `roleaction` VALUES (1, 20, 'admin', '2015-05-06 17:31:59', 'admin', '2015-05-06 17:31:59');
INSERT INTO `roleaction` VALUES (1, 21, 'admin', '2015-05-06 17:32:14', 'admin', '2015-05-06 17:32:14');
INSERT INTO `roleaction` VALUES (1, 22, 'admin', '2015-05-06 17:32:26', 'admin', '2015-05-06 17:32:26');
INSERT INTO `roleaction` VALUES (1, 23, 'admin', '2015-05-06 16:06:48', 'admin', '2015-05-06 16:06:48');
INSERT INTO `roleaction` VALUES (1, 24, 'admin', '2015-05-06 16:06:59', 'admin', '2015-05-06 16:06:59');
INSERT INTO `roleaction` VALUES (1, 25, 'admin', '2015-05-06 16:06:59', 'admin', '2015-05-06 16:06:59');
INSERT INTO `roleaction` VALUES (1, 26, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 27, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 28, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 29, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 30, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 31, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 32, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 33, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 34, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 35, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 36, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 37, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 38, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 39, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 40, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 41, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 42, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 43, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 44, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 45, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 46, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 47, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 48, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 49, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 50, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 51, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 52, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 53, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 54, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 55, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 56, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');
INSERT INTO `roleaction` VALUES (1, 57, 'admin', '2015-05-05 16:55:49', 'admin', '2015-05-05 16:55:49');

---

**Comment by johnfelipe** [comment]
Error
	consulta SQL:


	-- Volcar la base de datos para la tabla userrole

	INSERT INTO userrole VALUES (1, 1, 'admin', '2015-03-04 11:25:23', 'admin', '2015-03-04 11:25:23');
	MySQL ha dicho: Documentación

	#1452 - Cannot add or update a child row: a foreign key constraint fails (`curricullum`.`userrole`, CONSTRAINT `fk_userrole_role1` FOREIGN KEY (`roleid`) REFERENCES `role` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
