### ISSUE TITLE
He añadido datos y no se actualizan en el frontend

### ISSUE THREAD

**Issue by johnfelipe** [andresfranco/CV2#3]
http://localhost/CV2/main/en/1

![nada](https://cloud.githubusercontent.com/assets/428820/11415053/6af857a4-93cb-11e5-859c-6729986b1b10.png)

**Comment by andresfranco** [comment]
tienes que añadir los datos en translations dependiendo si es en ingles o español , en este caso no te salen por que no los has agregado en ingles.
